CREATE TABLE mahjong_room(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gameSateId BIGINT NOT NULL,
    roomCode INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    gameLength varchar(50) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
